[general]
	applicationID = "1445359551573655593"
	enabled = true
	debugging = false
	launcherIntegration = false
	rpcImageServer = false
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	version = 26

[init]
	enabled = true

	[[init.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "Loading..."
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[main_menu]
	enabled = true

	[[main_menu.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "In main menu"
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[server_list]
	enabled = true

	[[server_list.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "In main menu"
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[realms_list]
	enabled = true

	[[realms_list.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "In main menu"
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[join_game]
	enabled = true

	[[join_game.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "Joining a game..."
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[single_player]
	enabled = true

	[[single_player.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "In a lobby"
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[multi_player]
	enabled = true

	[[multi_player.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = "In a lobby"
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[realms]
	enabled = false

	[[realms.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[paused]
	enabled = false

	[[paused.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[generic]
	[[generic.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

[custom]
	enabled = false
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		[[dimension_overrides.dimensions.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		[[dimension_overrides.dimensions.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		[[dimension_overrides.dimensions.presence]]
		type = "PLAYING"
		description = "ðŸš‚ The Harpy Express: Extended"
		state = ""
		largeImageKey = ["icon"]
		largeImageText = "The Harpy Express: Extended"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

